[package]
name = "http"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
bitcask-rs ={ path = "../../bitcask-rs" }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
quote = "1.0.37"